import os
from pathlib import Path
from ultralytics import YOLO

# Set up paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
# This path is generated by format_dataset.py
DATASET_YAML = PROJECT_ROOT / "datasets" / "damaged-packages-sx9gw" / "custom_data.yaml"
WEIGHTS_DIR = PROJECT_ROOT / "ml" / "weights"

def train():
    print("🚀 Starting YOLOv8-Seg Training Pipeline for PDDS")
    
    if not DATASET_YAML.exists():
        print(f"❌ Error: Dataset config not found at {DATASET_YAML}")
        print("Please run download_dataset.py and format_dataset.py first.")
        return

    # Ensure weights directory exists
    WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)

    # We use YOLOv8 Nano segmentation model as it fits well in 4GB VRAM
    model = YOLO("yolov8n-seg.pt")

    print(f"📦 Loaded model. Starting training on {DATASET_YAML}...")
    
    # Training configuration optimized for 4GB VRAM (RTX 2050)
    results = model.train(
        data=str(DATASET_YAML),
        epochs=50,                  # Number of epochs
        imgsz=416,                  # Reduced image size to save VRAM
        batch=8,                    # Small batch size to prevent CUDA OOM
        workers=2,                  # Number of dataloader workers
        device=0,                   # Use GPU 0
        project=str(WEIGHTS_DIR),   # Where to save results
        name="pdds_v1",             # Run name
        patience=15,                # Early stopping
        save=True,                  # Save checkpoints
        exist_ok=True,              # Overwrite existing run with same name
        val=True,                   # Validate during training
        optimizer="AdamW",          # Good default optimizer
        lr0=0.001                   # Initial learning rate
    )

    print("\n✅ Training complete!")
    
    # The best weights are saved in weights/pdds_v1/weights/best.pt
    best_weights = WEIGHTS_DIR / "pdds_v1" / "weights" / "best.pt"
    print(f"💾 Best weights saved to: {best_weights}")
    print("Next step: Run 'python ml/training/evaluate.py' to check metrics.")

if __name__ == "__main__":
    train()
